Models/Artigo.cs
using System.Xml.Serialization;

namespace BlogSemedo.Models
{
    // using System.Xml.Serialization;
    // XmlSerializer serializer = new XmlSerializer(typeof(Artigo));
    // using (StringReader reader = new StringReader(xml))
    // {
    //    var test = (Artigo)serializer.Deserialize(reader);
    // }

    [XmlRoot(ElementName = "Artigo")]
    public class Artigo
    {

        [XmlElement(ElementName = "DataArtigo")]
        public string DataArtigo { get; set; }

        [XmlElement(ElementName = "Autor")]
        public string Autor { get; set; }

        [XmlElement(ElementName = "Titulo")]
        public string Titulo { get; set; }

        [XmlElement(ElementName = "Imagem")]
        public string Imagem { get; set; }

        [XmlElement(ElementName = "Resumo")]
        public string Resumo { get; set; }

        [XmlElement(ElementName = "CorpoArtigo")]
        public string CorpoArtigo { get; set; }
    }




}

Models/Blog.cs
namespace BlogSemedo.Models
{
    public class Blog
    {
        public Artigo Principal { get; set; }
        public Artigo DestaqueUm { get; set; }
        public Artigo DestaqueDois { get; set; }
        
        public List<Artigo> Artigos { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace BlogSemedo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ArtigosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting.Internal;
using System.Xml.Linq;
using BlogSemedo.Commom;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using System.Xml;
using BlogSemedo.Models;

namespace BlogSemedo.Controllers
{
    public class ArtigosController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;

        public ArtigosController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index(int? pageNumber)
        {
            var webRootPath = _hostingEnvironment.WebRootPath;
            var xmlFilePath = Path.Combine(webRootPath, "dados", "artigos");
            var artigos = new List<Artigo>();

            foreach (string file in Directory.EnumerateFiles(xmlFilePath, "*.xml"))
            {
                XmlDocument xmlDoc = new XmlDocument();
                xmlDoc.Load(file);
                var artigo = XmlHelper.Deserialize<Artigo>(xmlDoc.OuterXml);
                artigos.Add(artigo);
            }

            if (pageNumber == null)
            {
                pageNumber = 1;
                ViewBag.PageNumber = 1;
            }
            int itemsPerPage = 3;
            int startIndex = (pageNumber.Value - 1) * itemsPerPage;
            var pageItems = artigos.Skip(startIndex).Take(itemsPerPage);


            Blog blog = new Blog()
            {
                Artigos = pageItems.ToList(),
                DestaqueDois = PegarArtigo("destaques", "dois.xml"),
                DestaqueUm = PegarArtigo("destaques", "um.xml"),
                Principal = PegarArtigo("principal", "principal.xml")
            };

            return View(blog);
        }


        public  Artigo PegarArtigo(string subpasta,string nomeArquivo)
        {
            //var artigo = new Artigo();

            var webRootPath = _hostingEnvironment.WebRootPath;
            var xmlFilePath = Path.Combine(webRootPath, "dados", subpasta, nomeArquivo);

            XmlDocument xmlDoc = new XmlDocument();
            xmlDoc.Load(xmlFilePath);
            var artigo = XmlHelper.Deserialize<Artigo>(xmlDoc.OuterXml);

            return artigo;
        }
    }
}

Controllers/HomeController.cs
using BlogSemedo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogSemedo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Artigos/Index.cshtml
@model BlogSemedo.Models.Blog
<div class="p-4 p-md-5 mb-4 rounded text-bg-dark">
   <div class="col-md-6 px-0">
      <h1 class="display-4 fst-italic">@Model.Principal.Titulo</h1>
      <p class="lead my-3">@Model.DestaqueUm.Resumo</p>
      <p class="lead mb-0"><a href="#" class="text-white fw-bold">Continue reading...</a></p>
   </div>
</div>
<div class="row mb-2">
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-success">Design</strong>
                <h3 class="mb-0">@Model.DestaqueUm.Titulo</h3>
                <div class="mb-1 text-body-secondary">@Model.DestaqueUm.DataArtigo</div>
                <p class="mb-auto"> @Model.DestaqueUm.Resumo</p>
                <a href="#" class="stretched-link">Continue reading</a>
            </div>
            <div class="col-auto d-none d-lg-block">
                <img class="bd-placeholder-img" src="@Model.DestaqueUm.Imagem" width="200" height="250"/>
            </div>
        </div>
    </div>
   <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
         <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-success">Design</strong>
            <h3 class="mb-0">@Model.DestaqueDois.Titulo</h3>
            <div class="mb-1 text-body-secondary">@Model.DestaqueDois.DataArtigo</div>
            <p class="mb-auto"> @Model.DestaqueDois.Resumo</p>
            <a href="#" class="stretched-link">Continue reading</a>
         </div>
          <div class="col-auto d-none d-lg-block">
              <img class="bd-placeholder-img" src="@Model.DestaqueDois.Imagem" width="200" height="250"/>
   
          </div>
      </div>
   </div>
</div>
<div class="row g-5">
   <div class="col-md-8">
      <h3 class="pb-4 mb-4 fst-italic border-bottom">
         From the Firehose
      </h3>
       @foreach (var item in Model.Artigos)
        {
            <article class="blog-post">
                <h2 class="blog-post-title mb-1">@item.Titulo</h2>
                    <p class="blog-post-meta">@item.DataArtigo by <a href="#">@item.Autor </a></p>
                <p>
                    @Html.Raw( @item.CorpoArtigo) 
                </p>
            </article>           
        }

       <nav class="blog-pagination" aria-label="Pagination">
         <a class="btn btn-outline-primary rounded-pill" href="#">Older</a>
         <a class="btn btn-outline-secondary rounded-pill disabled">Newer</a>
      </nav>
   </div>
   <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
         <div class="p-4 mb-3 bg-body-tertiary rounded">
            <h4 class="fst-italic">About</h4>
            <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
         </div>
         <div class="p-4">
            <h4 class="fst-italic">Archives</h4>
            <ol class="list-unstyled mb-0">
               <li><a href="#">March 2021</a></li>
               <li><a href="#">February 2021</a></li>
               <li><a href="#">January 2021</a></li>
               <li><a href="#">December 2020</a></li>
               <li><a href="#">November 2020</a></li>
               <li><a href="#">October 2020</a></li>
               <li><a href="#">September 2020</a></li>
               <li><a href="#">August 2020</a></li>
               <li><a href="#">July 2020</a></li>
               <li><a href="#">June 2020</a></li>
               <li><a href="#">May 2020</a></li>
               <li><a href="#">April 2020</a></li>
            </ol>
         </div>
         <div class="p-4">
            <h4 class="fst-italic">Elsewhere</h4>
            <ol class="list-unstyled">
               <li><a href="#">GitHub</a></li>
               <li><a href="#">Twitter</a></li>
               <li><a href="#">Facebook</a></li>
            </ol>
         </div>
      </div>
   </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogSemedo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogSemedo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogSemedo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artigos" asp-action="Index">Artigos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - BlogSemedo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<div id="loom-companion-mv3" ext-id="liecbddmkiiihnedobmlmillhodjkdmb"><section id="shadow-host-companion"></section></div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>